dataSource:
    provider: HikariDataSource
    hikari:
        driverClassName: org.h2.Driver
        jdbcUrl: jdbc:h2:mem:test
        username: root
        password: root

executor:
    enableAsync: true
    async:
        maxThreadPoolSize: 10